################################################
## Packages / Home-Assistant
################################################
---
# Welcome to my Home Assistant configuration!
# This is a very modular HS Config
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
